config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: 'registrations'}
  root 'pages#home'

  get 'home' => 'pages#home', as: 'home'
  get 'contact' => 'pages#contact', as: 'contact'
  get 'about' => 'pages#about', as: 'about'
  get 'manage' => 'pages#manage', as: 'manage'
  get 'confirmed' => 'orders#confirmed', as: 'confirmed'
  get 'completed' => 'orders#order_completed', as: 'order_completed'
  get 'notifications' => 'notifications#index', as: 'notifications'
  get 'carts/show'
  get 'menu/' => 'products#menu', as: "menu"
  get 'profile' => 'users#profile', as: "profile"
  patch 'upload_avatar' => 'users#upload_avatar', as: 'upload_avatar'

  resources :promotions, except: [:edit] do
    member do
      get 'change_status' => 'promotions#change_status', as: 'change_status'
    end
  end
  resources :products, except: [:edit]
  resources :categories, except: [:edit]
  put 'update_status/:id' => 'orders#update_status', as: 'update_status'
  resources :orders, except: [:destroy, :edit] do
    member do
      get 'my_order' => 'orders#user_order', as: 'user'
      get 'order_items' => 'orders#client_order', as: 'show_client'
      get 'all_orders_client' => 'orders#all_client_orders', as: 'all_client'
    end
  end
  resources :order_items, only: [:create, :update, :destroy]
  resources :reservations do
    member do
      put 'reservation_accepted' => 'reservations#change_status_accepted', as: 'accepted'
      put 'reservation_declined' => 'reservations#change_status_declined', as: 'declined'
    end
  end
  resources :tables, except: [:edit]
  resources :users, except: [:edit]
  resource :cart, only: [:show]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= Person.new
    access_abilities(user.person)
  end

  def access_abilities(user)
    if user.has_role? :client
      can [:show, :index], [Product, Order]
      cannot :access, [Category, Table]
    end
    if user.has_role?  :waiter
      cannot [:edit, :destroy], [Category, Table, Product]
      cannot [:destroy], [Reservation]
      cannot [:profile], [User]
    end
    if user.has_role?  :cook
    end
    if user.has_role?  :manager
      # can :manage, :all
      can :access, [User]
      can :access, :action_index_user
    end
    if user.has_role?  :boss
      can :manage, :all
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :name, presence: true
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :order
  
  Type = [
    Error = 'error',
    Notice = 'notice',
    Alert = 'alert',
    Success = 'success'
  ]
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :notifications
  has_many :order_items
  belongs_to :table
  accepts_nested_attributes_for :order_items

  # validates :user, presence: true
  validates :status, presence: true

  before_create :set_order_status
  before_save :update_subtotal

  Statuses = [
            Reservation = "Reservation",
            New = "New",
            Inprogress = "InProgress",
            Done = "Done",
            Payed = "Payed",
            Closed = "Closed"
            ]

  scope :draft, -> { where.not(status: Order::New) }
  scope :anew, -> { where(status: Order::New) }
  scope :inprogress, -> { where(status: Order::Inprogress) }
  scope :done, -> { where(status: Order::Done) }
  scope :payed, -> { where(status: Order::Payed) }
  scope :closed, -> { where(status: Order::Closed) }
  scope :reservation, -> { where(status: Order::Reservation) }

  def title
    "#{self.id}-#{self.created_at.strftime("%d/%m/%Y")}"
  end

  def subtotal
    self.order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  private
  def set_order_status
    self.status = Order::New
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product

  validate :available_quantity
  validate :product_present
  validate :order_present

  attr_accessor :category, :description
  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
  def available_quantity
    if self[:quantity] > product.quantity
      errors.add(:quantity, "Please order only what's available")
    end
  end

  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/person.rb
require 'rubygems'
require 'role_model'
class Person < ActiveRecord::Base
  include RoleModel

  belongs_to :user

  roles_attribute :roles_mask
  roles :manager, :client, :cook, :waiter, :boss
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "missing_user.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def full_name
    "#{self.first_name} #{self.last_name}".rstrip
  end

  def form_completed?(current_user)
    current_user.person.first_name.present? &&
    current_user.person.last_name.present? &&
    current_user.person.tel.present? ? true : false
  end
end

app/models/point.rb
class Point < ActiveRecord::Base
  scope :active, -> { where(is_active: true).first }
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :order_items

  validates :name, presence: true
  validates :category, presence: true

  has_attached_file :image, styles: { medium: "200x200!", thumb: "100x100!" }, default_url: "missing.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  default_scope { where(is_active: true) }

  UnitType = [Grams = 'g', ML = 'ml', Piece = 'piece']
  
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300!", thumb: "100x100!" }, default_url: "missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :table
  belongs_to :user
  belongs_to :order

  validates :release_at, presence: true
  validates :table_id, presence: true

  Statuses = [New = 'New', Accepted = 'Accepted', Declined = 'Declined']

  scope :declined, -> { where(status: Reservation::Declined)}
  scope :active, -> { where.not(status: Reservation::Declined)}
  scope :accepted, -> { where(status: Reservation::Accepted)}
  scope :finished, -> {where('release_at < ?', DateTime.now)}
  scope :today, -> {where('release_at.to_date = ?', DateTime.now.to_date)}
  scope :today_finished,
    -> {where('release_at < ? && release_at.to_date = ?', DateTime.now, DateTime.now.to_date)}
  scope :today_future,
    -> {where('release_at > ? && release_at.to_date = ?', DateTime.now, DateTime.now.to_date)}
  scope :future, -> {where('release_at.to_date > ?', DateTime.now.to_date)}
  scope 'order?', -> {where('order_id IS NOT NULL')}
end

app/models/table.rb
class Table < ActiveRecord::Base
  has_many :reservations
  has_many :orders
  validates :nr, presence: true
  validates :quantity, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :reservations
  has_many :notifications
  has_one  :person, dependent: :destroy

  accepts_nested_attributes_for :person

  def full_name_or_email
    if self.person
      "#{self.person.try(:first_name)} #{self.person.try(:last_name)}"
    else
      self.email
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/partials/_advert.html.haml
.container_12
  %h3
  .grid_3
    .box.maxheight
      =image_tag "box_img1.jpg"
      .title Lorem Ipsum
      Integer convallis orci vel mi nelaoreet, at ornare lorem consequat. Phasellus era nisl auctor vel veliterol.
      %br/
      %a{:href => "#"} More Info
  .grid_3
    .box.maxheight
      =image_tag "box_img2.jpg"
      .title Aliquamh ante
      Benteger convallis orci veli elaoreet, at ornare loremo konsequat. Phasellus era nisl auctor vel veliterut.
      %br/
      %a{:href => "#"} More Info
  .grid_3
    .box.maxheight
      =image_tag "box_img3.jpg"
      .title Ulum volutpat
      Hrtolieger convallis omi tem aore, at ornare loren coate. Pasellus era nisl auctor vel veliterolsed pharetra.
      %br/
      %a{:href => "#"} More Info
  .grid_3
    .box.maxheight
      =image_tag "box_img4.jpg"
      .title Vestibulum volu
      Convallis orci vel mi oreet, at kotornare lorem consequat. Sellus era nisl auctor vel veliterolvenenatis nulla.
      %br/
      %a{:href => "#"} More Info

app/views/partials/_content.html.haml
.content
  = yield

app/views/partials/_devise_links.html.haml
- if user_signed_in?
  .pull-right= link_to 'Logout', destroy_user_session_path, :method => :delete, class:"btn"
  .pull-right= link_to 'Profile',  profile_path, class:"btn"
- else
  .pull-right= link_to 'Login', new_user_session_path, class:"btn"
  .pull-right= link_to 'Sign up', new_user_registration_path, class:"btn"

app/views/partials/_footer.html.haml
%footer
  .container_12
    .grid_6.prefix_3
      %a.f_logo{:href => "#"}
        =image_tag "f_logo.png"
      .copy
        \© 2015 |
        %a{:href => "#"} Privacy Policy
        %br/
        Website   designed by
        %a{:href => "http://www.templatemonster.com/", :rel => "nofollow"} TemplateMonster.com

app/views/partials/_header.html.haml
%header
  = render partial: 'partials/devise_links'
  .container_12
    .grid_12
      .socials
        %a{:href => "#"}
        %a{:href => "#"}
        %a{:href => "#"}
        %a.last{:href => "#"}
      %h1
        %a{:href => root_path}
          =image_tag "logo.png"
      .menu_block
        %nav#bt-menu.bt-menu
          %a.bt-menu-trigger{:href => "#"}
            %span Menu
          -if user_signed_in? && !(current_user.person.has_role? :client)
            = render partial: 'partials/menu/menu'
          -else
            = render partial: 'partials/menu/client'

        .clear
      .clear
      .center.store
        = link_to "My Store", root_path
        .cart-text= render 'layouts/cart_text'

app/views/partials/_news.html.haml
%a.block1{:href => "#"}
  =image_tag "blur_img1.jpg"
  %span.price
    %span magna non nunc
    %span
      %small $
      29.35
    %strong
%a.block1{:href => "#"}
  =image_tag "blur_img2.jpg"
  %span.price
    %span terto nomino
    %span
      %small $
      35.45
    %strong
%a.block1{:href => "#"}
  =image_tag "blur_img3.jpg"
  %span.price
    %span metus feugiat
    %span
      %small $
      50.10
    %strong

app/views/partials/_products_new.html.haml
.grid_12
  %h3.head3 Our other products
-@products_news.each do |product|
  .news
    %time{:datetime => "2013-01-01"}
      Sept
      %span 04
    .extra_wrapper
      = image_tag product.image.url(:thumb)
      %p.col1>
        = link_to product.name, product_path(product.id)
      = product.description



  -# .grid_3
  -#   .box.maxheight
  -#     = image_tag product.image.url(:thumb)
  -#     .title
  -#       =link_to product.name, product_path(product.id), class: 'btn btn-link'
  -#     = product.description

app/views/partials/menu/_client.html.haml
%ul
  %li.current.bt-icon
    %a{:href => root_path} Home
  %li.bt-icon
    =link_to "Menu", menu_path
  %li.bt-icon
    =link_to "Promotions", promotions_path
  %li.bt-icon
    =link_to "Reservation", new_reservation_path
  %li.bt-icon
    = link_to "About", about_path
  %li.bt-icon
    = link_to "Contacts", contact_path

app/views/partials/menu/_menu.html.haml
%ul
  %li.current.bt-icon
    %a{:href => root_path} Home
  %li.bt-icon
    =link_to "Menu", menu_path
  %li.bt-icon
    = link_to "Orders", orders_path(tab: Order::Reservation)
  %li.bt-icon
    =link_to "Reservations", reservations_path
  %li.bt-icon
    =link_to "Manage", manage_path
  %li.bt-icon
    =link_to "Users", users_path(tab: 'manager')