config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: 'registrations'}
  root 'pages#home'

  get 'home' => 'pages#home', as: 'home'
  get 'contact' => 'pages#contact', as: 'contact'
  get 'about' => 'pages#about', as: 'about'
  get 'manage' => 'pages#manage', as: 'manage'
  get 'confirmed' => 'orders#confirmed', as: 'confirmed'
  get 'completed' => 'orders#order_completed', as: 'order_completed'
  get 'notifications' => 'notifications#index', as: 'notifications'
  get 'carts/show'
  get 'menu/' => 'products#menu', as: "menu"
  get 'profile' => 'users#profile', as: "profile"
  patch 'upload_avatar' => 'users#upload_avatar', as: 'upload_avatar'

  resources :promotions, except: [:edit] do
    member do
      get 'change_status' => 'promotions#change_status', as: 'change_status'
    end
  end
  resources :products, except: [:edit]
  resources :categories, except: [:edit]
  put 'update_status/:id' => 'orders#update_status', as: 'update_status'
  resources :orders, except: [:destroy, :edit] do
    member do
      get 'my_order' => 'orders#user_order', as: 'user'
      get 'order_items' => 'orders#client_order', as: 'show_client'
      get 'all_orders_client' => 'orders#all_client_orders', as: 'all_client'
    end
  end
  resources :order_items, only: [:create, :update, :destroy]
  resources :reservations do
    member do
      put 'reservation_accepted' => 'reservations#change_status_accepted', as: 'accepted'
      put 'reservation_declined' => 'reservations#change_status_declined', as: 'declined'
    end
  end
  resources :tables, except: [:edit]
  resources :users, except: [:edit]
  resource :cart, only: [:show]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :reservations
  has_many :notifications
  has_one  :person, dependent: :destroy

  accepts_nested_attributes_for :person

  def full_name_or_email
    if self.person
      "#{self.person.try(:first_name)} #{self.person.try(:last_name)}"
    else
      self.email
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:tab] == 'manager'
      @persons = Person.where(roles_mask: 1).paginate(page: params[:page], per_page: 10)
    elsif params[:tab] == 'client'
      @persons = Person.where(roles_mask: 2).paginate(page: params[:page], per_page: 10)
    elsif params[:tab] == 'cook'
      @persons = Person.where(roles_mask: 4).paginate(page: params[:page], per_page: 10)
    elsif params[:tab] == 'waiter'
      @persons = Person.where(roles_mask: 8).paginate(page: params[:page], per_page: 10)
    elsif params[:tab] == 'boss'
      @persons = Person.where(roles_mask: 16).paginate(page: params[:page], per_page: 10)
    else
      @persons = Person.all.paginate(page: params[:page], per_page: 10)
    end
  end

  def show
    @user = User.find(params[:id])
    @user.build_person if !@user.person.present?
  end

  def new
    @user = User.new
    @user.build_person if !@user.person.present?
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.points += Point.active.form_completed if Point.active.present? && @user.person.form_completed?
      @user.points += Point.active.registration if Point.active.present?
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      @user.points += Point.active.avatar if Point.active.present? && @user.person.form_completed?
      redirect_to user_path(@user)
    else
      render :show
    end
  end

  def profile
    @user = current_user
    @user.build_person if !@user.person.present?
    @orders = @user.orders.draft
    @reservations = @user.reservations.active
  end

  def upload_avatar
    @person = current_user.person
    @person.avatar = params[:user][:person_attributes][:avatar]
    if @person.save
      current_user.points += Point.active.avatar if Point.active.present?
      redirect_to profile_path(tab: 'avatar')
    else
      redirect_to :back
    end
  end

  private

  def user_params
    params.require(:user).permit(:id, :email, person_attributes: [:id, :first_name,
      :last_name, :tel, :roles, :user_id])
  end

  def person_params
    params.require(:person).permit(:roles, :user_id, :first_name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/profile/_avatar.html.haml
=form_for @user, url: upload_avatar_path, html: { multipart: true } do |f|
  .form-group
    = image_tag @user.person.avatar.url(:medium)
  =f.fields_for :person do |p|
    .form-group.avatar
      =p.file_field :avatar
  = f.submit 'Upload',  class: 'btn btn-primary avatar'

app/views/users/profile/_orders.html.haml
%table.table.profile
  %thead
    %th Date
    %th Status
  %tbody
    -@orders.each do |o|
      %tr
        %th
          = link_to o.created_at.strftime("%d-%m-%Y %H:%M"), user_order_path(o.id)
        %th
          = o.status

app/views/users/profile/_personal_info.html.haml
=form_for @user do |f|
  .form-body
    .form-group
      %label.email
      =f.text_field :email, :placeholder => "E-mail:", class: 'form-control'
    =f.fields_for :person do |p|
      .form-group
        %label.name
        =p.text_field :first_name, :placeholder => "Name:", class: 'form-control'
      .form-group
        %label.name
        =p.text_field :last_name, :placeholder => "Surname:", class: 'form-control'
      .form-group
        %label
        =p.text_field :tel, :placeholder => "Phone:", class: 'form-control'
    = f.submit "Update", class: 'btn btn-primary'

app/views/users/profile/_reservations.html.haml
%table.table.profile
  %thead
    %th Table
    %th Order
    %th Date
    %th Status
    %th Actions
  %tbody
    -@reservations.each do |r|
      %tr
        %th
          = r.table_id
        %th
          = link_to "Order", user_order_path(r.order_id) if r.order.present?
        %th
          = r.release_at.strftime("%d-%m-%Y %H:%M")
        %th
          = r.status
        %th
          = link_to "Delete", reservations_path(r.id), method: :delete, class: 'btn btn-danger'