config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: 'registrations'}
  root 'pages#home'

  get 'home' => 'pages#home', as: 'home'
  get 'contact' => 'pages#contact', as: 'contact'
  get 'about' => 'pages#about', as: 'about'
  get 'manage' => 'pages#manage', as: 'manage'
  get 'confirmed' => 'orders#confirmed', as: 'confirmed'
  get 'completed' => 'orders#order_completed', as: 'order_completed'
  get 'notifications' => 'notifications#index', as: 'notifications'
  get 'carts/show'
  get 'menu/' => 'products#menu', as: "menu"
  get 'profile' => 'users#profile', as: "profile"
  patch 'upload_avatar' => 'users#upload_avatar', as: 'upload_avatar'

  resources :promotions, except: [:edit] do
    member do
      get 'change_status' => 'promotions#change_status', as: 'change_status'
    end
  end
  resources :products, except: [:edit]
  resources :categories, except: [:edit]
  put 'update_status/:id' => 'orders#update_status', as: 'update_status'
  resources :orders, except: [:destroy, :edit] do
    member do
      get 'my_order' => 'orders#user_order', as: 'user'
      get 'order_items' => 'orders#client_order', as: 'show_client'
      get 'all_orders_client' => 'orders#all_client_orders', as: 'all_client'
    end
  end
  resources :order_items, only: [:create, :update, :destroy]
  resources :reservations do
    member do
      put 'reservation_accepted' => 'reservations#change_status_accepted', as: 'accepted'
      put 'reservation_declined' => 'reservations#change_status_declined', as: 'declined'
    end
  end
  resources :tables, except: [:edit]
  resources :users, except: [:edit]
  resource :cart, only: [:show]

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :order_items

  validates :name, presence: true
  validates :category, presence: true

  has_attached_file :image, styles: { medium: "200x200!", thumb: "100x100!" }, default_url: "missing.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  default_scope { where(is_active: true) }

  UnitType = [Grams = 'g', ML = 'ml', Piece = 'piece']
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def menu
    @categories = Category.order(order_number: :asc)
    @products = Product.all
    if current_order
      @order_item = current_order.order_items
    else
      current_order = Order.new
      @order_item = current_order.order_items.new
    end
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
    @products_news= Product.all.sample(3)
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to :back
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to :back
    else
      render :show
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to menu_path
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :weight, :quantity,
     :price, :image, :is_active, :unit)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product_row.html.haml
.well
  .row
    .col-md-8
      %h4= product.name
    .col-md-4
      = form_for order_item, remote: true do |f|
        %h4.text-right
          Unit Price:
          %span{:style => "color: green"}= number_to_currency product.price

          = f.number_field :quantity, class: "form-control", min: 1
          .input-group-btn
            = f.hidden_field :product_id, value: product.id
            = f.submit "Add to Cart", class: "btn btn-primary"

app/views/products/_products.html.haml
.div-tabs
  .tab-content.gallery1
    .grid_12{style: 'margin-left: 120px'}
      -products.each do |p|
        .grid_3.product_image
          =link_to "#", class: "gal" do
            =image_tag p.image.url(:medium), class: "col3"
            %span
          .col5
            = form_for @order_item.find_by(product_id: p.id) || current_order.order_items.new, remote: true do |f|
              %div.col5{style: 'min-height: 40px'}
                =link_to p.name, product_path(p.id), class: 'price_link'
              %p= number_to_currency(p.price)
              .col-lg-4.col-lg-offset-3= f.number_field :quantity, value: f.object.quantity, class: "form-control", style:'width: 54px', min: 0
              = f.hidden_field :product_id, value: p.id
              = f.submit "Add to Cart", class: "btn btn-primary"

app/views/products/index.html.haml
.container
  %h3 Listing products
  %table.table
    %thead
      %tr
        %th Category
        %th Name
        %th Price
        %th Weight
        %th Unit
        %th Quantity
        %th Image
        %th Change to
        %th Created at
        %th{:colspan => "2"}
    %tbody
      -@products.each do |product|
        %tr
          %td= link_to product.category.name, categories_path(product.category)
          %td= product.name
          %td= product.price
          %td= product.weight
          %td= product.unit
          %td= product.quantity
          %td= image_tag product.image.url(:thumb)
          %td= (product.is_active ? (link_to 'Deactive', "#", class: 'btn btn-link') : (link_to "Active", "#", class: 'btn btn-link'))
          %td= product.created_at.strftime("%d-%m-%Y %H:%M")
          %td= link_to 'Show', product_path(product)
          %td= link_to 'Destroy', product_path(product), method: :delete, data: { confirm: 'Are you sure?' }

app/views/products/menu.html.haml
.content
  .container_12
    .grid_12
      %h3.head2 Our Menu
    .tabs.tb.gallery
      .div-nav
        .grid_12
          %ul.nav
            -@category_first = @categories.to_a.shift
            %li{class: params[:tab].blank? || params[:tab] == @category_first.name ? 'selected' : ''}
              %a{:href => "?tab=#{@category_first.name}"}
                = @category_first.name

            -@categories.each do |c|
              %li{class: params[:tab] == "#{c.name}" ? 'selected' : ''}
                %a{:href => "?tab=#{c.name}"}
                  = c.name
        = render partial: 'products', locals: {products: params[:tab].blank? ? @category_first.products : Category.find_by(name:params[:tab]).products}

app/views/products/new.html.haml
.row
  .col-md-12
    = form_for(@product) do |f|
      - if @product.errors.any?
        #error_explanation
          %h2
            = pluralize(@product.errors.count, "error")
            prohibited this order from being saved:
          %ul
            - @product.errors.full_messages.each do |message|
              %li= message
      %h4.center= "Add new product"
      .form-horizontal
        .form-group
          = f.label :category, :class => 'col-md-3 control-label'
          .col-md-7
            = f.collection_select :category_id, Category.all, :id, :name, {}, :class => 'form-control'
        .form-group
          = f.label :name, :class => 'col-md-3 control-label'
          .col-md-7
            = f.text_field :name, :class => 'form-control'
        .form-group
          = f.label :price, :class => 'col-md-3 control-label'
          .col-md-7
            = f.price_field :price, :class => 'form-control'
        .form-group
          = f.label :weight, :class => 'col-md-3 control-label'
          .col-md-7
            = f.number_field :weight, :class => 'form-control'
        .form-group
          = f.label :unit, :class => 'col-md-3 control-label'
          .col-md-7
            = f.number_field :unit, :class => 'form-control'
        .form-group
          = f.label :quantity, :class => 'col-md-3 control-label'
          .col-md-7
            = f.number_field :quantity, :class => 'form-control'
        .form-group
          = f.label :description, :class => 'col-md-3 control-label'
          .col-md-7
            = f.text_area :description, :class => 'form-control'
        .form-group
          = f.label :image, :class => 'col-md-3 control-label'
          .col-md-7
            = image_tag @product.image.url(:thumb) if !@product.new_record?
            =f.file_field :image
        .form-group
          .col-sm-offset-2.col-sm-10
            .checkbox
              %b
                = f.check_box :is_active, :class => 'col-md-3'
                = f.label :is_active, "Active", :class => 'col-md-1 control-label'
        %div.margin-top-10
          .center=f.button "Save", :class=>"btn btn-primary", :type=>'submit'

app/views/products/show.html.haml
-if current_user && (current_user.person.has_any_role? :boss, :manager)
  = render partial: "products/show/manage_products"
-else
  = render partial: "products/show/show_product"