config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: 'registrations'}
  root 'pages#home'

  get 'home' => 'pages#home', as: 'home'
  get 'contact' => 'pages#contact', as: 'contact'
  get 'about' => 'pages#about', as: 'about'
  get 'manage' => 'pages#manage', as: 'manage'
  get 'confirmed' => 'orders#confirmed', as: 'confirmed'
  get 'completed' => 'orders#order_completed', as: 'order_completed'
  get 'notifications' => 'notifications#index', as: 'notifications'
  get 'carts/show'
  get 'menu/' => 'products#menu', as: "menu"
  get 'profile' => 'users#profile', as: "profile"
  patch 'upload_avatar' => 'users#upload_avatar', as: 'upload_avatar'

  resources :promotions, except: [:edit] do
    member do
      get 'change_status' => 'promotions#change_status', as: 'change_status'
    end
  end
  resources :products, except: [:edit]
  resources :categories, except: [:edit]
  put 'update_status/:id' => 'orders#update_status', as: 'update_status'
  resources :orders, except: [:destroy, :edit] do
    member do
      get 'my_order' => 'orders#user_order', as: 'user'
      get 'order_items' => 'orders#client_order', as: 'show_client'
      get 'all_orders_client' => 'orders#all_client_orders', as: 'all_client'
    end
  end
  resources :order_items, only: [:create, :update, :destroy]
  resources :reservations do
    member do
      put 'reservation_accepted' => 'reservations#change_status_accepted', as: 'accepted'
      put 'reservation_declined' => 'reservations#change_status_declined', as: 'declined'
    end
  end
  resources :tables, except: [:edit]
  resources :users, except: [:edit]
  resource :cart, only: [:show]

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :table
  belongs_to :user
  belongs_to :order

  validates :release_at, presence: true
  validates :table_id, presence: true

  Statuses = [New = 'New', Accepted = 'Accepted', Declined = 'Declined']

  scope :declined, -> { where(status: Reservation::Declined)}
  scope :active, -> { where.not(status: Reservation::Declined)}
  scope :accepted, -> { where(status: Reservation::Accepted)}
  scope :finished, -> {where('release_at < ?', DateTime.now)}
  scope :today, -> {where('release_at.to_date = ?', DateTime.now.to_date)}
  scope :today_finished,
    -> {where('release_at < ? && release_at.to_date = ?', DateTime.now, DateTime.now.to_date)}
  scope :today_future,
    -> {where('release_at > ? && release_at.to_date = ?', DateTime.now, DateTime.now.to_date)}
  scope :future, -> {where('release_at.to_date > ?', DateTime.now.to_date)}
  scope 'order?', -> {where('order_id IS NOT NULL')}
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!, except: [:create, :new]

  def index
    if current_user.person.has_any_role? :boss, :manager
      @reservations = Reservation.active
    else
      @reservations = Reservation.accepted
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if params[:reservation][:email].blank?
      authenticate_user!
    else
      @reservation.status = Reservation::New
    end
    @reservation.user = current_user if current_user
    if @reservation.save
      session[:reservation]= @reservation.id if !current_user
      redirect_to menu_path, notice: 'You can create an order'
    else
      render :new
    end
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update_attributes(reservation_params)
      redirect_to reservation_path(@reservation)
    else
      render :show
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    if @reservation.destroy
      redirect_to reservations_path
    end
  end

  def change_status_accepted
    @reservation = Reservation.find(params[:id])
    @reservation.update_attributes(status: Reservation::Accepted)
    redirect_to :back
  end

  def change_status_declined
    @reservation = Reservation.find(params[:id])
    @reservation.update_attributes(status: Reservation::Declined)
    redirect_to :back
  end

  private

  def reservation_params
    params.require(:reservation).permit(:table_id, :order_id, :release_at,
    :user_id, :s, :email)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/index/_manage_reservations.html.haml
.container
  %h3 Listing reservation
  %table.table
    %thead
      %tr
        %th User
        %th Table
        %th Order
        %th Status
        %th Release at
        %th Created at
        %th{:colspan => "4"}
    %tbody
      -@reservations.each do |reservation|
        %tr
          %td= reservation.user.try(:email) || reservation.email
          %td= reservation.table_id
          -if reservation.order
            %td= link_to reservation.order_id, order_path(order_id)
          -else
            %td
          %td= reservation.status
          %td= reservation.release_at.strftime("%d-%m-%Y %H:%M")
          %td= reservation.created_at.strftime("%d-%m-%Y %H:%M")
          %td= link_to "Accept", accepted_reservation_path(reservation), method: :put, class: 'btn btn-success'
          %td= link_to "Decline", declined_reservation_path(reservation), method: :put, class: 'btn btn-danger'
          %td= link_to 'Show', reservation_path(reservation)
          %td= link_to 'Destroy', reservation_path(reservation), method: :delete, data: { confirm: 'Are you sure?' }

app/views/reservations/index/_show_reservations.html.haml
.container
  %h3 Listing reservation
  %table.table
    %thead
      %tr
        %th User
        %th Table
        %th Order
        %th Release at
        %th Status
        %th Created at
        %th{:colspan => "2"}
    %tbody
      -@reservations.each do |reservation|
        %tr
          %td= reservation.user.try(:email) || reservation.email
          %td= reservation.table_id
          -if reservation.order
            %td= link_to reservation.order_id, order_path(order_id)
          -else
            %td
          %td= reservation.release_at.strftime("%d-%m-%Y %H:%M")
          %td= reservation.status
          %td= reservation.created_at.strftime("%d-%m-%Y %H:%M")
          %td= link_to 'Show', reservation_path(reservation)